//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLGeneration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLGeneration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference was made to a source without defining an alias for it..
        /// </summary>
        internal static string AliasRequired {
            get {
                return ResourceManager.GetString("AliasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a null or blank column name..
        /// </summary>
        internal static string BlankColumnName {
            get {
                return ResourceManager.GetString("BlankColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a null or blank datatype name..
        /// </summary>
        internal static string BlankDataType {
            get {
                return ResourceManager.GetString("BlankDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a null or blank expression type..
        /// </summary>
        internal static string BlankExpressionType {
            get {
                return ResourceManager.GetString("BlankExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a null or blank function name..
        /// </summary>
        internal static string BlankFunctionName {
            get {
                return ResourceManager.GetString("BlankFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a null or blank expression item name..
        /// </summary>
        internal static string BlankItemName {
            get {
                return ResourceManager.GetString("BlankItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a null or blank parameter name..
        /// </summary>
        internal static string BlankParameterName {
            get {
                return ResourceManager.GetString("BlankParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a null or blank parameter prefix..
        /// </summary>
        internal static string BlankParameterPrefix {
            get {
                return ResourceManager.GetString("BlankParameterPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a null or blank schema name..
        /// </summary>
        internal static string BlankSchemaName {
            get {
                return ResourceManager.GetString("BlankSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a null or blank table name..
        /// </summary>
        internal static string BlankTableName {
            get {
                return ResourceManager.GetString("BlankTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a null or blank expected token value..
        /// </summary>
        internal static string BlankTokenValue {
            get {
                return ResourceManager.GetString("BlankTokenValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to define two expressions items with the same name..
        /// </summary>
        internal static string DuplicateExpressionItemName {
            get {
                return ResourceManager.GetString("DuplicateExpressionItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a duplicate source name: {0}. Use an alias to distinguish between multiple references to the same table..
        /// </summary>
        internal static string DuplicateSourceName {
            get {
                return ResourceManager.GetString("DuplicateSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to define two tokens with the same name: {0}..
        /// </summary>
        internal static string DuplicateTokenDefinition {
            get {
                return ResourceManager.GetString("DuplicateTokenDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to create a case expression without any cases..
        /// </summary>
        internal static string EmptyCaseExpression {
            get {
                return ResourceManager.GetString("EmptyCaseExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to build an empty filter clause..
        /// </summary>
        internal static string EmptyFilterGroup {
            get {
                return ResourceManager.GetString("EmptyFilterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to specify an empty namespace..
        /// </summary>
        internal static string EmptyNamespace {
            get {
                return ResourceManager.GetString("EmptyNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to build a join without any filters..
        /// </summary>
        internal static string EmptyOnExpression {
            get {
                return ResourceManager.GetString("EmptyOnExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all expression types have a handler assigned to them..
        /// </summary>
        internal static string MissingHandlers {
            get {
                return ResourceManager.GetString("MissingHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row count cannot be negative when defining a bound function window frame..
        /// </summary>
        internal static string NegativeRowCount {
            get {
                return ResourceManager.GetString("NegativeRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to build a select command without any projections..
        /// </summary>
        internal static string NoProjections {
            get {
                return ResourceManager.GetString("NoProjections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to build a compound command without any commands..
        /// </summary>
        internal static string NoQueries {
            get {
                return ResourceManager.GetString("NoQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to build an update statement without any setters..
        /// </summary>
        internal static string NoSetters {
            get {
                return ResourceManager.GetString("NoSetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered unexpected token: {0}..
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unknown conjunction type..
        /// </summary>
        internal static string UnknownConjunction {
            get {
                return ResourceManager.GetString("UnknownConjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unknown distinct qualifier..
        /// </summary>
        internal static string UnknownDistinctQualifier {
            get {
                return ResourceManager.GetString("UnknownDistinctQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unknown windowed function frame type..
        /// </summary>
        internal static string UnknownFrameType {
            get {
                return ResourceManager.GetString("UnknownFrameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unknown null placement..
        /// </summary>
        internal static string UnknownNullPlacement {
            get {
                return ResourceManager.GetString("UnknownNullPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unknown ordering..
        /// </summary>
        internal static string UnknownOrder {
            get {
                return ResourceManager.GetString("UnknownOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unknown quantifier..
        /// </summary>
        internal static string UnknownQuantifier {
            get {
                return ResourceManager.GetString("UnknownQuantifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to retrieve an column source: {0}..
        /// </summary>
        internal static string UnknownSource {
            get {
                return ResourceManager.GetString("UnknownSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unknown token type..
        /// </summary>
        internal static string UnknownTokenType {
            get {
                return ResourceManager.GetString("UnknownTokenType", resourceCulture);
            }
        }
    }
}
